services:
  # Config Server (レプリカセット)
  cfg1:
    image: mongo:7
    command: ["mongod","--configsvr","--replSet","cfgRS","--bind_ip_all"]
  cfg2:
    image: mongo:7
    command: ["mongod","--configsvr","--replSet","cfgRS","--bind_ip_all"]
  cfg3:
    image: mongo:7
    command: ["mongod","--configsvr","--replSet","cfgRS","--bind_ip_all"]

  # Shard1 (レプリカセット)
  shard1a:
    image: mongo:7
    command: ["mongod","--shardsvr","--replSet","shard1","--bind_ip_all"]
  shard1b:
    image: mongo:7
    command: ["mongod","--shardsvr","--replSet","shard1","--bind_ip_all"]

  # Shard2 (レプリカセット)
  shard2a:
    image: mongo:7
    command: ["mongod","--shardsvr","--replSet","shard2","--bind_ip_all"]
  shard2b:
    image: mongo:7
    command: ["mongod","--shardsvr","--replSet","shard2","--bind_ip_all"]

  # mongos (ルータ)
  mongos:
    image: mongo:7
    depends_on: [cfg1, cfg2, cfg3, shard1a, shard1b, shard2a, shard2b]
    ports: ["27018:27017"]
    command: [
      "mongos",
      "--configdb","cfgRS/cfg1:27017,cfg2:27017,cfg3:27017",
      "--bind_ip_all"
    ]
